version: "1.1"
"on": {}
stages:
  - stage:
      - git-checkout:
          alias: git-checkout
          description: 代码仓库克隆
          version: "1.0"
          params:
            branch: ((gittar.branch))
            depth: 1
            password: ((gittar.password))
            uri: ((gittar.repo))
            username: ((gittar.username))
  - stage:
      - golang:
          alias: golang
          version: "1.0"
          params:
            command: go run main.go
            context: ${git-checkout}
          resources:
            cpu: 0.2
            mem: 1024
