version: "1.1"
"on": {}
cron: 0 35 9 * * *
cron_compensator:
  enable: false
  latest_first: true
  stop_if_latter_executed: true
stages:
  - stage:
      - git-checkout:
          alias: git-checkout
          description: 代码仓库克隆
          version: "1.0"
          params:
            branch: ((gittar.branch))
            depth: 1
            password: ((gittar.password))
            uri: ((gittar.repo))
            username: ((gittar.username))
  - stage:
      - custom-script:
          alias: custom-script
          description: 运行自定义命令
          version: "1.0"
          commands:
            - cd ${git-checkout}
            - go run main.go
          resources:
            cpu: 0.2
            mem: 1024
